spring:
  application:
    name: savr
  datasource:
    url: jdbc:postgresql://localhost:5432/segundo_exemplo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: true
    open-in-view: false
